### ISSUE TITLE
Fedora & Redhat packaging

### ISSUE THREAD

**Issue by topazus** [hardinfo2/hardinfo2#15]
Hello, I am a Fedora packager and I would like to package hardinfo2 into Fedora official repository.

- Fix desktop file, https://github.com/hardinfo2/hardinfo2/pull/14
- Why currently all RPM flavours uses libsoup-2.4? I tested it with libsoup-3.0, it seems works fine.

https://github.com/hardinfo2/hardinfo2/blob/3cf771f9d7fa3299a649963d85847024e551627c/CMakeLists.txt#L153-L156

**Comment by topazus** [comment]
> Libsoup3 is just implemented and seams to work, but had some debugging issues, so it needs more testing.
> 
> This program was so unfortunate to loose the server as berlios shut down their free services. So we have a lot of older distros to update, as hardinfo has not been released for >10 years.
> 
> The backporting is done and for fedora/redhat we can go back to at least FC23 and Centos6 which do not have libsoup3.
> 
> Having the same libsoup2.4 in all distros simplifies the choices in CMakeLists.txt and makes it simpler to support bug reports for initial first release. But yes, later we release with libsoup3 for those distros supporting that.

Ok, I see. I will use libsoup2.4 to make the package for now, and I opened a review request on redhat bugzilla, https://bugzilla.redhat.com/show_bug.cgi?id=2267901


> The package must be released as hardinfo to upgrade existing packages. Branding as hardinfo2 2.0.x is to could create a community edition. You have been invited as member of organisation - we do the same for all other distro maintainers.

Do you suggest the package name as `hardinfo`? I use package name of hardinfo2 on above posted review request.

**Comment by hwspeedy** [comment]
We have to keep the package name as hardinfo - it is also the same program - just a community fork - this repo can live forever. And we have to upgrade all the lost programs - SBC (Single Board Computers) are not always on active maintained distro releases - but typically there are backporting repositories that can be used - this project supports those making those repositories also.

The developer of hardinfo is backup maintainer on the community fork, she is just busy right now.
This you can see under owners, when you accept the request to join organization. 
The plan is to always have 3 project maintainers, that are owners of repo and has unlimited access to the domain hardinfo2.org - this ensures the survival of the project.

**Comment by topazus** [comment]
I have a trouble here. How to properly run the hardinfo2 that is built from source code?

```bash
❯ ./build/hardinfo2 

** (hardinfo2:11566): ERROR **: 22:46:38.666: Failed to find runtime data.

• Is HardInfo2 correctly installed?
• See if share/hardinfo2 and /usr/local/lib64/hardinfo2 exists and you have read permission.
Trace/breakpoint trap (core dumped)
```

**Comment by hwspeedy** [comment]
@topazus

**Packagename: hardinfo**

**Fedora Status**
Fedora maintainer: topazus
previous inactive maintainer: adel gadllah


**Debian Status**
Debian maintainer: original Simon Quiqley (no answer) - lucascastro will try contacting him and submit to debian within a couple of weeks.
Talks with debian mentors on oftc indicate, that it is also possible to continue the hardinfo package naming in debian. Suggests just changing the upstream repo.


PS: Can you remove this trial - Seams to be active though I never got it to accept source package, thanx.
https://bugzilla.redhat.com/show_bug.cgi?id=2267587

**Comment by topazus** [comment]
> PS: Can you remove this trial - Seams to be active though I never got it to accept source package, thanx.
> https://bugzilla.redhat.com/show_bug.cgi?id=2267587

Acctually, I do not understand you words here. I opened a new review request here, https://bugzilla.redhat.com/show_bug.cgi?id=2267901, and I asked another Fedora packager who have the right to approve the package review to see this. You can free to close this, https://bugzilla.redhat.com/show_bug.cgi?id=2267587, because I will do the packaging job.

**Comment by hwspeedy** [comment]
> I have a trouble here. How to properly run the hardinfo2 that is built from source code?

I have not been able to run directly from source build, as it needs all the libraries & data in place. eg. "make install"
 - it will need some relative search paths in source code to run directly from build without install - the relative path could be different for each distro build...

PS: bug 2267587 closed.

**Comment by hwspeedy** [comment]
@topazus 

I see there is a problem in building fc39 - missing man page -  that is fixed by adding this patch:
https://github.com/hardinfo2/hardinfo2/commit/e8e223b4103badddb92b7727ed8386ea8896921d.patch

FC39 had a problem with the man pages - that is now fixed in FC39.

**Comment by hwspeedy** [comment]
@topazus - we continue with package name hardinfo2, please add obsolete hardinfo to hardinfo2.spec, thanx

**PACKAGE NAME: hardinfo2
To upgrade existing hardinfo packages:
rpm spec OBSOLETE=hardinfo
deb spec BREAK+REPLACE=hardinfo**

**Comment by topazus** [comment]
I looked at the source code of this and did a rough license analysis, it contains some files that are under other licenses, except the GPL-2.0-or-later. Here are some examples:
```
# most of the source code is GPL-2.0-or-later license, except:
# includes/blowfish.h - LGPL-2.1-or-later
# includes/loadgraph.h - LGPL-2.0-only
# deps/uber-graph/g-ring.c: LGPL-2.1-or-later
# deps/uber-graph/g-ring.h: LGPL-2.1-or-later
# deps/uber-graph/uber-graph.c: GPL-3.0-or-later
# deps/uber-graph/uber-graph.h: GPL-3.0-or-later
# deps/uber-graph/uber-heat-map.c: GPL-3.0-or-later
# deps/uber-graph/uber-heat-map.h: GPL-3.0-or-later
# deps/uber-graph/uber-label.c: GPL-3.0-or-later
# deps/uber-graph/uber-label.h: GPL-3.0-or-later
# deps/uber-graph/uber-line-graph.c: GPL-3.0-or-later
# deps/uber-graph/uber-line-graph.h: GPL-3.0-or-later
# deps/uber-graph/uber-range.c: GPL-3.0-or-later
# deps/uber-graph/uber-range.h: GPL-3.0-or-later
# deps/uber-graph/uber-scale.c: GPL-3.0-or-later
# deps/uber-graph/uber-scale.h: GPL-3.0-or-later
# deps/uber-graph/uber-scatter.c: GPL-3.0-or-later
# deps/uber-graph/uber-scatter.h: GPL-3.0-or-later
# deps/uber-graph/uber-window.c: GPL-3.0-or-later
# deps/uber-graph/uber-window.h: GPL-3.0-or-later
# deps/uber-graph/uber.h: GPL-3.0-or-later
# modules/benchmark/blowfish.c - LGPL-2.1-or-later
```
So I think it needs to add other license files to repo.

**Comment by hwspeedy** [comment]
**License**
So multiple files in root like: LICENSE.1 LICENSE.2 with GPL3.0+, LGPL2.1+ ??
PS: includes/loadgraph.h is also LGPL-2.1+

**Build/test**
I have tried your hardinfo2.spec build with the tools/create_fedora_source.sh - that does not work for me - benchmarks does not run any more and it seams sluggish. Do you see the same? - any clue?

the build instructions that also creates a fedora package on the README.md works great.
NOTE: FC39 needs CMakeLists.txt - set(PACKAGE_MANPAGES 0) for CPack build. FC38 does not - Any clue to that?

**Comment by topazus** [comment]
> I have tried your hardinfo2.spec build on fc39 with the tools/create_fedora_source.sh in master checkout - that does not work for me - benchmarks do not run any more and it seams sluggish. Do you see the same? - any clue?

You can do the following to build RPM packages
```bash
cd tools/
# download source, it is in $HOME/SOURCES
spectool hardinfo2.spec
# build source and binary RPM package
rpmbuild -ba hardinfo2.spec
# source RPM is in directory $HOME/rpmbuild/SRPMS
# binary RPM is in $HOME/RPMS/x86_64 on x86-64 arch.
```

As the benchmark mentioned above, do you mean run benchmark during building RPM package?

**Comment by topazus** [comment]
> PS: includes/loadgraph.h is also LGPL-2.1+

Thanks for the tip. I am not good at identifying license issues, which match the license words with its corresponding SPDX license expression.

**Comment by topazus** [comment]
For now, I have no idea with that it stuck in benchmarking... with the RPM package built by hardinfo2.spec

**Comment by topazus** [comment]
But it seems that the benchmark did run from the output of `hardinfo2 -r`. see: https://gist.github.com/topazus/b7ac7d9767cdf13dabbad26aeb5380d2

**Comment by hwspeedy** [comment]
**Regarding rpmbuild failing benchmark in GUI**

My best guess is that we are seeing the symptoms of errors in source code. 

Why the two packages are so different, I do not know. 
Seams the compiler settings could be different. Ninja was not an issue, nor release vs debug.

But the exchange of sysbench.so was a difference also the library loading was different due to bad design. 

After looking into the code and fixing these issues and more - I think we might be having a stable build in both scenarios (rpmbuild and cpack) - I will have to do a lot more testing - but first some sleep. 

Submitted to master with https://github.com/hardinfo2/hardinfo2/commit/1ea9d8e74a2b6131cddd1d56d0fb8f16250e613f

**Comment by hwspeedy** [comment]
Fedora 39 build - Please ask who ever you know at fedora to upgrade cmake to 3.28.x - It is a flaw in cmake/cpack that is the fault of man pages.

https://gitlab.kitware.com/cmake/cmake/-/issues/25545

**Comment by topazus** [comment]
> After looking into the code and fixing these issues and more - I think we might be having a stable build in both scenarios (rpmbuild and cpack) - I will have to do a lot more testing - but first some sleep.
> 
> Submitted to master with [1ea9d8e](https://github.com/hardinfo2/hardinfo2/commit/1ea9d8e74a2b6131cddd1d56d0fb8f16250e613f)

Good. With the commit change as patch with rpmbuild, hardinfo2 gui can benchmark now instead of getting stuck in benchmarking...


> Fedora 39 build - Please ask who ever you know at fedora to upgrade cmake to 3.28.x - It is a flaw in cmake/cpack that is the fault of man pages.
> 
> https://gitlab.kitware.com/cmake/cmake/-/issues/25545

Ok, I will open a bugzilla or email to inform the package maintainer of CMake.

**Comment by mckaygerhard** [comment]
Hi, @hwspeedy  you must change the name and the references.. may you have problems in future and also there is some directions that you dont get into.. 

you development is too hurry  and bypass to much things.. some people that was in dessire to package get back to hardinfo original one.. or will fork.. 

too much fork will cause more problems rather than solutions.. cos ghost always back to future.. please .. be more consent of the things

**Comment by hwspeedy** [comment]
@topazus very nice - good job. I will start testing backport and other distros. 
Looking forward to feedback from fedora review on the package for currently maintained fedora distros.
Then we wait for debian maintainer and see if it creates any changes and gets that in sync with fedora.
And then we do an updated release.


@mckaygerhard please do not spam - any other distro maintainer - please open a new issue and tell what distro you are creating packages for and we will see what we can do to help you, thanx.

**Comment by hwspeedy** [comment]
@topazus 
It seams the package has errors at Fedora Review as NEW.po is included in package. I have fixed that with this patch:
https://github.com/hardinfo2/hardinfo2/commit/62466d1fb8875139b40dc05194e0b39ceaa968ea.patch

Please update, thanx.

**Comment by topazus** [comment]
> It seams the package has errors at Fedora Review as NEW.po is included in package. I have fixed that with this patch:
> https://github.com/hardinfo2/hardinfo2/commit/62466d1fb8875139b40dc05194e0b39ceaa968ea.patch

https://src.fedoraproject.org/rpms/hardinfo2 is created. Can you publish new release? So I do not need to apply the above patch files or get source from specfic commit when importing

**Comment by hwspeedy** [comment]
Thanx, Its approved by fedora - Sounds like a good to do new release - will do new release now.

**Comment by hwspeedy** [comment]
Version 2.0.15 ready:

https://github.com/hardinfo2/hardinfo2/releases/tag/release-2.0.15

**Comment by topazus** [comment]
Ok, the package was built and published on Fedora. https://bodhi.fedoraproject.org/updates/?packages=hardinfo2

**Comment by hwspeedy** [comment]
Thank you so much, @topazus - Wonderful job and guidance, thanx.

**Comment by topazus** [comment]
@hwspeedy Actually, I can also build the RPM package for EPEL. https://docs.fedoraproject.org/en-US/epel/

I tested it on epel 8 and epel 9, on epel 9 it built successfully, on epel 8 it failed. https://copr.fedorainfracloud.org/coprs/topazus/epel/build/7131872/

So I built it on epel 9. https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2024-e080b91480

**Comment by hwspeedy** [comment]
@topazus 
I will look into epel8.

The deprecated inet functions (inet_addr,inet_ntoa) should be fixed with this patch:
https://github.com/hardinfo2/hardinfo2/commit/de70603e7a490a20d6eeee923c7764e426880a86.patch

**Comment by hwspeedy** [comment]
@topazus 
**Regarding epel8 redhat building**
 - I can see from redhat build logs, that it is the linker not working. 
 - There is no error message that can be used - have you found debug info we can use? 

**ninja**
One thing, that you do differently from my CPack builds is the ninja building
 - is that an requirement for fedora/redhat? - Otherwise try without ninja.
When we go back to older distros the ninja feature might either not be available or have issues...

I can see that hartbuzz is not linked in on el8 but is on el9. 
hartbuzz is installed by dependencies so there is a good change, that it is needed transitively by eg. GTK3.

PS: Works fine on my el8 with "cmake -DCMAKE_BUILD_TYPE=Release ..;make -j"

**Comment by topazus** [comment]
> **Regarding epel8 redhat building**
> 
>     * I can see from redhat build logs, that it is the linker not working or a hardened-cc1 error (See bottom of this message).
> 
>     * There is no error message that can be used - have you found debug info we can use?
> 
> 
> **ninja** One thing, that you do differently from my CPack builds is the ninja building
> 
>     * is that an requirement for fedora/redhat? - Otherwise try without ninja.
>       When we go back to older distros the ninja feature might either not be available or have issues... (Just an idea)

I also don't know how to get the debug info during the building package on epel 8. I tried built the package without `-GNinja` on epel 8, it still failed. https://download.copr.fedorainfracloud.org/results/topazus/epel/epel-8-x86_64/07132126-hardinfo2/builder-live.log.gz


> **hardened-cc1** maybe because redhat uses hardened-cc1: sudo dnf install redhat-rpm-config
> 
> https://gist.github.com/yograterol/99c8e123afecc828cb8c

The `redhat-rpm-config` package seems to be installed already.



> **But the license is special.**
> 
>     * License     : GPL-2.0-or-later AND LGPL-2.1-or-later AND GPL-1.0-or-later AND LGPL-2.0-or-later AND GPL-3.0-or-later AND GPL-2.0-only AND LGPL-2.1-only AND LGPL-2.0-only
> 
>     * Correct right now: GPL-2.0-or-later AND LGPL-2.1-or-later AND GPL-3.0-or-later
> 
>     * Project license is: GPL-2.0-or-later

I may not see it extensively. Btw, I used [scancode-toolkit](https://github.com/nexB/scancode-toolkit/) to generate the information about the license issue.



> **Regarding machine architectures**
> I see we are creating for IBM mainframes - nice - but we are missing fedora RISC-V architecture - How to do that?
> This program is really good for SBC (Single Board Computers) - like the uprising star RISC-V machines.
> Tested for risc-v on Starfive vision 2, Lichee pi 4A. Both works great and no bugs left unfixed.

The risc-v architecture has not been supported on Fedora koji build system.

**Comment by hwspeedy** [comment]
@topazus 
Can you try epel 7 build?


**Building system for fedora risc-v**

http://fedora.riscv.rocks/koji/

Do you know how that is connected to copr, koji and bodhi? or maybe know who to ask - the must be feed from fedora packaging to riscv somehow...

**Comment by topazus** [comment]
> **Building system for fedora risc-v**
> 
> http://fedora.riscv.rocks/koji/
> 
> Do you know how that is connected to copr, koji and bodhi? or maybe know who to ask - there must be some feed from fedora packaging to riscv somehow...

The risc-v is not ready for official supported arch for now.
[1] https://discussion.fedoraproject.org/t/risc-v-server-spec-for-fedora-koji-system-as-builder/35264/11

[2] https://lists.fedorahosted.org/archives/list/devel@lists.fedoraproject.org/thread/Z2RR2OE5TAQH5CVJ5VB5T3R7OM5ULYPQ/#QZ5WZ33D2NZXR4O447WD3ELV2BTC5VJY

**Comment by hwspeedy** [comment]
@topazus 

**I think that EL8 is building in source dir - there is a directory called hardinfo2 - same as linker output.**


from you build debug log: https://download.copr.fedorainfracloud.org/results/topazus/epel/epel-8-x86_64/07132126-hardinfo2/builder-live.log.gz

**EL8 - BAD**
 /usr/bin/cmake -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_BUILD_TYPE=Release
CMake Warning:
  **No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.**

**EL9 - GOOD**
+ /usr/bin/cmake -S . -B redhat-linux-build -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON -GNinja -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is GNU 11.4.1

**NO ERROR BUILDING IN SOURCE DIR**

**Comment by hwspeedy** [comment]
**License check up:**
There are two LGPL2.0 files - so the correct license is:
**GPL-2.0-or-later AND LGPL-2.1 AND LGPL-2.1-or-later AND GPL-3.0-or-later**

Added tools/check_license.sh to master - uses licensecheck (exists in both debian/fedora)

https://github.com/hardinfo2/hardinfo2/commit/25ba15be2ab92fbadbd4a766e3ae961666c2ade7

**Comment by topazus** [comment]
> **I think that EL8 is building in source dir - there is a directory called hardinfo2 - same as linker output.**

Thanks for the helpful investigation. The build on epel 8 passed now. The build on epel 7 failed because of cmake minimum version constraint. https://download.copr.fedorainfracloud.org/results/topazus/epel/epel-7-x86_64/07140996-hardinfo2/builder-live.log.gz

all buils on epel: https://copr.fedorainfracloud.org/coprs/topazus/epel/build/7140996/

**Comment by hwspeedy** [comment]
@topazus 
Very nice, good job.

**el7** can build using cmake3 from epel repository, instead of cmake.

**el6** is difficult to build as it needs scl (Scientific linux) compiler tools 3.

**Comment by topazus** [comment]
> **License check up:**
> There are two LGPL2.1-only files - so the correct license is:
> **GPL-2.0-or-later AND LGPL-2.1-only AND LGPL-2.1-or-later AND GPL-3.0-or-later**

https://github.com/hardinfo2/hardinfo2/blob/b010c80a8d4327931db1595534c2adede5ff3168/hardinfo2/gg_strescape.c#L1-L18

The license here seemed to be `LGPL-2.0-or-later` license.

https://github.com/hardinfo2/hardinfo2/blob/b010c80a8d4327931db1595534c2adede5ff3168/includes/binreloc.h#L1-L11

The code that is under public domain should be located and opened the PR like this, 
https://gitlab.com/fedora/legal/fedora-license-data/-/merge_requests/486/diffs

https://docs.fedoraproject.org/en-US/legal/update-existing-packages/#_public_domain

**Comment by hwspeedy** [comment]
relicenses 3 public domain as GPL2+ (Project license)
fixed detection issues and updated tools/check_license.sh (use from master)

commit:
https://github.com/hardinfo2/hardinfo2/commit/4ddedff3fa107fdf2f229c258bd9dfd6c6223b3b

check_license.sh from master
https://github.com/hardinfo2/hardinfo2/blob/master/tools/check_license.sh

**Comment by topazus** [comment]
If you re-license public domain to GPL-2.0-or-later, `includes/sha1.h` file is not re-licensed accordingly.

**Comment by hwspeedy** [comment]
Thanx, - Relicensed "includes/sha1.h", added credits to binreloc.c+h

https://github.com/hardinfo2/hardinfo2/commit/65ef92c3a4baed206b6aeb4142dca88016fdfc35

**Comment by topazus** [comment]
I checked the following files are related to `LGPL-2.0-or-later` license, can you double check them?



```
# hardinfo2/gg_strescape.c: LGPL-2.0-or-later
# hardinfo2/util.c: GPL-2.0-or-later AND LGPL-2.0-or-later
# deps/uber-graph/uber-frame-source.c: LGPL-2.0-or-later
# deps/uber-graph/uber-frame-source.h: LGPL-2.0-or-later
# deps/uber-graph/uber-timeout-interval.c: LGPL-2.0-or-later
# deps/uber-graph/uber-timeout-interval.h: LGPL-2.0-or-later
```

> **License check up:**
> There are two LGPL2.1-only files - so the correct license is:
> **GPL-2.0-or-later AND LGPL-2.1-only AND LGPL-2.1-or-later AND GPL-3.0-or-later**

If the above files are LGPL-2.0-or-later, so the correct license is `GPL-2.0-or-later AND LGPL-2.1-only AND LGPL-2.1-or-later AND GPL-3.0-or-later AND LGPL-2.0-or-later`

**Comment by hwspeedy** [comment]
I agree with licenses, thanx.

**Comment by hwspeedy** [comment]
@topazus 
I can see that you got el7 to work also - so nice, great job 👍 

I also see that you are making trials on el6 - I have tested and successfully build on ol6 and it needs a patch for el6 to disable HARDINFO2_GTK3=0:
https://github.com/hardinfo2/hardinfo2/commit/117d8a65243e964f2f6996709171de75a6f5b1a4

If you cannot get the cern scentific linux into the Redhat building system for package "devtoolset-3" - **it is not the end of the world..**
https://linux-archive.web.cern.ch/updates/slc6/

This is just going great - amazing, thank you so much.

**Comment by topazus** [comment]
The package built on epel 7 has been pushed the update. https://bodhi.fedoraproject.org/updates/?packages=hardinfo2

I cannot build the package on epel 6. Its status is EOL. https://pagure.io/fedora-infrastructure/issue/9481

**Comment by hwspeedy** [comment]
Exactly EL6 is extended EOL in 2 months - Thank you so much!
 - I will put you into the app credits at next update - fantastic work.

**Comment by hwspeedy** [comment]
@topazus 
Working great with packaging fedora/redhat branches, thanx alot.

Can you also add opensuse/suse packaging? - seams they are maybe through the same release channels...

**Comment by topazus** [comment]
The openSUSE packages is on https://build.opensuse.org/,  whether third-party or official? But I am not official openSUSE packager, so I can only do it as third-party packaging.
The fedora copr which can do third-party RPM packaging for Fedora, as well as openSUSE: https://copr.fedorainfracloud.org/. But I currently do not use openSUSE. Maybe @hillwoodroc are more familiar with openSUSE packaging.

**Comment by hwspeedy** [comment]
Thanx @topazus @hillwoodroc

Just saw the openSUSE was in COPR and guessed that fedora also provided build system packages for openSUSE. Seams from openSUSE build page, that you send - that the old hardinfo **official package** has/had a package maintainer: Perhaps @Xrevan86

https://build.opensuse.org/search/owner?owner=1&search_text=hardinfo&devel=off&devel=on&limit=1

Would be nice for the SUSE/openSUSE users to be upgraded to the rebooted hardinfo2 also.

The old hardinfo repo now points to this repo as upstream - see https://github.com/lpereira/hardinfo/blob/master/README.md

anyone that has rights to package for official SUSE/openSUSE library is welcome to package the new rebooted hardinfo2 package.

**Just create a new issue with packaging for SUSE/openSUSE, thanx**

https://github.com/hardinfo2/hardinfo2/releases/tag/release-2.0.18
