### ISSUE TITLE
SSD NVME size detected as 0

### ISSUE THREAD

**Issue by superbonaci** [hardinfo2/hardinfo2#58]
```
# fdisk -l /dev/nvme0n1
Disk /dev/nvme0n1: 238.47 GiB, 256060514304 bytes, 500118192 sectors
Disk model: THNSN5256GPU7 TOSHIBA                   
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: E5B48D12-4C5B-11EC-81D3-0242AC130003
```

This is the Storage report:

```

Devices
*******


Storage
-------

-UDisks2-
     nvme0n1	TOSHIBA THNSN5256GPU7 TOSHIBA	0.0 B

```

The partition is detected:

![toshiba](https://github.com/user-attachments/assets/4c174023-7dec-40ac-b199-76aba8b3019c)

**Comment by hwspeedy** [comment]
@superbonaci 
Thanx for reporting your findings - always better with one too many than one too little.

1. I do not see the same issue.
2. The Partition table is right about nvme drive size..
3. The size information is from udisks2 - so that is where the issue should be reported.

I will close the issue - but anyone can continue to add more input to this issue thread, that might be important to hardinfo2, thanx.

**Comment by DisboardTetta** [comment]
I encountered the same problem.
<img width="406" height="43" alt="Image" src="https://github.com/user-attachments/assets/0c73a575-d49f-4151-8f08-670ad9dfbb6c" />
You said that the problem is in udisks2. I decided to check it by running the command
```
udisksctl info -b /dev/nvme0n1 | grep '\sSize:'
```
and got a very specific result
> Size: 512110190592
At the same time, I also see all the sections through your software on this disk with the correct size.

**Comment by hwspeedy** [comment]
The size it read from udisks2 using it's DBUS interface.

See hardinfo2/udisks2_util.c - L514

v = get_dbus_property(drive, UDISKS2_DRIVE_INTERFACE, "Size");
if (v){
        u->size = g_variant_get_uint64(v);
        g_variant_unref(v);
}

If udisksctl also reads via DBUS - it is something else in hardinfo2.

**Comment by hwspeedy** [comment]
Picture of working debian 12 nvme storage - NUC:

<img width="1282" height="1027" alt="Image" src="https://github.com/user-attachments/assets/13a828a9-671f-4ffd-99d6-cbb1f475c7fc" />

Anything different that either of you can see?

**Comment by hwspeedy** [comment]
@DisboardTetta CC:@superbonaci 

> Also, I looked at the open issue in the udisk2 project, and found that their parameter of interest is tnvmcap, but I suggest that, provided that tnvmcap = 0, look at Size and give it instead of 0. Unless, of course, you use nvm-cli bypassing udisk

Found the mentioned udisks2 issue for NVME disk size=0:
https://github.com/storaged-project/udisks/pull/1230

It's a udisks2 issue - maybe semi fixed in some distros... - See above PR1230
There seams to be nothing we can do as invalid SSD NVME namespaces removes the possibility to use namespace info instead of disk size reported...

**Comment by superbonaci** [comment]
Issue still reproducible with `Toshiba THNSN5256GPU7`.

Size is shown when asking by block device but when asking for drive it gets you 0:

```
```
